# Generated by Django 4.2.10 on 2024-09-13 09:34

from django.db import migrations, models

import bitswan_backend.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_brokers_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokers",
            name="url",
            field=models.URLField(),
        ),
    ]
