# Generated by Django 4.2.10 on 2025-08-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20250811_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupNavigation',
        ),
    ]
