# Generated by Django 4.2.10 on 2025-08-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_hub', '0002_alter_dashboardentry_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardEntry',
        ),
    ]
