# Generated by Django 4.2.10 on 2025-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('keycloak_org_id', models.CharField(max_length=255)),
                ('automation_server_id', models.CharField(max_length=255)),
            ],
        ),
    ]
