# Generated by Django 4.2.10 on 2025-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_created_at_workspace_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('automation_server_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('keycloak_org_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
