# Generated by Django 4.2.10 on 2025-05-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_automationserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationserver',
            name='automation_server_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='automation_server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.automationserver', to_field='automation_server_id'),
        ),
    ]
