# Generated by Django 4.2.10 on 2025-05-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_automationserver_automation_server_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='automation_server_id',
            new_name='automation_server',
        ),
    ]
