# Generated by Django 4.2.10 on 2025-05-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_rename_automation_server_id_workspace_automation_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='automation_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspaces.automationserver', to_field='automation_server_id'),
        ),
    ]
