# Generated by Django 4.2.10 on 2025-08-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0008_alter_workspace_id"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO core_automationserver (automation_server_id, name, keycloak_org_id, created_at, updated_at)
            SELECT automation_server_id, name, keycloak_org_id, created_at, updated_at FROM workspaces_automationserver;

            INSERT INTO core_workspace (id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at)
            SELECT id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at FROM workspaces_workspace;
            """,
            reverse_sql="""
            INSERT INTO workspaces_automationserver (automation_server_id, name, keycloak_org_id, created_at, updated_at)
            SELECT automation_server_id, name, keycloak_org_id, created_at, updated_at FROM core_automationserver;

            INSERT INTO workspaces_workspace (id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at)
            SELECT id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at FROM core_workspace;
            """,
        ),
    ]
