# workspaces.00xx_copy_to_core
# Generated by Django 4.2.10 on 2025-08-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0008_alter_workspace_id"),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Copy automation servers first to satisfy FK on core_workspace
            INSERT INTO core_automationserver (automation_server_id, name, keycloak_org_id, created_at, updated_at)
            SELECT automation_server_id, name, keycloak_org_id, created_at, updated_at
            FROM workspaces_automationserver
            ON CONFLICT (automation_server_id) DO NOTHING;

            INSERT INTO core_workspace (id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at)
            SELECT id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at
            FROM workspaces_workspace
            ON CONFLICT (id) DO NOTHING;
            """,
            reverse_sql="""
            INSERT INTO workspaces_automationserver (automation_server_id, name, keycloak_org_id, created_at, updated_at)
            SELECT automation_server_id, name, keycloak_org_id, created_at, updated_at
            FROM core_automationserver
            ON CONFLICT (automation_server_id) DO NOTHING;

            INSERT INTO workspaces_workspace (id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at)
            SELECT id, name, keycloak_org_id, automation_server_id, created_at, editor_url, updated_at
            FROM core_workspace
            ON CONFLICT (id) DO NOTHING;
            """,
        ),
    ]
