# Generated by Django 4.2.10 on 2025-08-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_auto_20250811_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='automation_server',
        ),
        migrations.DeleteModel(
            name='AutomationServer',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
