version: "3.0"

volumes:
  portainer_data:
  influx_data:
  influx_config:
  postgres-keycloak-data:
  emqx_data:
  bitswan_backend_production_postgres_data: {}
  bitswan_backend_production_postgres_data_backups: {}
  bitswan-editor-data:

services:
  influxdb:
    image: influxdb:2.0
    restart: always
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    env_file:
      - .influxdb.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always

  emqx:
    image: emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    env_file:
      - .emqx.env
    volumes:
      - emqx_data:/opt/emqx/data

  keycloak:
    image: bitswan/bitswan-keycloak:2024-9110295480-git-d7a8e49
    container_name: "aoc-keycloak"
    restart: always
    env_file:
      - .keycloak.env
    command: start-dev

  postgres:
    image: postgres:12-bullseye
    container_name: "aoc-keycloak-postgres"
    restart: always
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    env_file: .keycloak-postgres.env

  mailhog:
    image: mailhog/mailhog
    restart: always

  automation-operation-centre:
    container_name: "automation-operation-centre"
    restart: always
    image: bitswan/automation-operations-centre:2024-11950867795-git-5ff440c
    env_file: .operations-centre.env
    ports:
      - "3000:3000"

  bitswan-backend:
    image: bitswan/bitswan-backend:2024-12279082742-git-b86a560
    depends_on:
      - bitswan-backend-postgres
    restart: always
    networks:
      - bitswan_network
    env_file:
      - .bitswan-backend.env
      - .bitswan-backend-postgres.env
    ports:
      - 5000:5000
    command: /start

  bitswan-backend-postgres:
    image: postgres:15-bullseye
    restart: always
    networks:
      - bitswan_network
    volumes:
      - bitswan_backend_production_postgres_data:/var/lib/postgresql/data
      - bitswan_backend_production_postgres_data_backups:/backups
    env_file:
      - .bitswan-backend-postgres.env

networks:
  bitswan_network:
    external: false
