version: "3.0"

volumes:
  portainer_data:
  influx_data:
  influx_config:
  mosquitto_data:
  mosquitto_log:
  postgres-keycloak-data:
  emqx_data:
  bitswan-editor-data:

services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
    environment:
      - DOMAIN="http://platform.local"
    networks:
      default:
        aliases:
          - "platform.local"
          - "poc.platform.local"
          - "influx.platform.local"
          - "keycloak.platform.local"

  influxdb:
    image: influxdb:2.0
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    env_file:
      - .influxdb.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"

  emqx:
    image: emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    environment:
      - EMQX_DASHBOARD__DEFAULT_PASSWORD="foo"
    volumes:
      - emqx_data:/opt/emqx/data

  keycloak:
    image: bitswan/bitswan-keycloak:2024-9110295480-git-d7a8e49
    restart: always
    ports:
      - "9090:8080"
    env_file:
      - .keycloak.env
    command: start-dev

  postgres:
    image: postgres:12-bullseye
    restart: always
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    env_file: .postgres.env

  # mailhog:
  #   image: mailhog/mailhog
  #   restart: always
  #   ports:
  #     - "8025:8025" # Web UI
  #     - "1025:1025" # SMTP server

  automation-operation-centre:
    restart: always
    image: bitswan/automation-operations-centre:2024-11950867795-git-5ff440c
    env_file: .aoc.env
    ports:
      - "3000:3000"

  profile-manager:
    restart: always
    image: bitswan/profile-manager:2024-11950867793-git-5ff440c
    volumes:
      - ./profile-manager/discovery_service.yaml:/conf/config.yaml:r
      - ./profile-manager/navigation_menu.json:/conf/navigation_menu.json
      - ./profile-manager/navigation_schema.json:/conf/navigation_schema.json:r

  bitswan-editor:
    image: bitswan/bitswan-editor:2024-11177396408-git-b7f80e5
    restart: always
    ports:
      - "10000:8080"
    entrypoint: ["/usr/bin/entrypoint.sh", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "."]
    # entrypoint: ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."] # Uncomment this line to enable authentication
    environment:
      - BITSWAN_DEPLOY_URL=http://gitops:8079
      - BITSWAN_DEPLOY_SECRET=secret
    volumes:
      - bitswan-editor-data:/home/coder

  # Linux GITOPS
  gitops:
    image: bitswan/gitops:2024-11950964487-git-7e7eb51
    restart: always
    privileged: true
    pid: host
    ports:
      - "8079:8079"
    volumes:
      - /path/to/repo:/repo # Change this to the path of your repository
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/bitswan-secrets/:/etc/bitswan-secrets/
    environment:
      - BS_BITSWAN_DIR=/repo
      - BS_HOST_DIR=/path/to/repo # Change this to the path of your repository
      - MQTT_BROKER=mosquitto
      - MQTT_TOPIC=/c/local/running-pipelines/topology
      - HOST_PATH: $PATH
      - HOST_HOME: $HOME
      - HOST_USER: $USER

  # Windows/MacOS GITOPS
  # gitops:
  #   image: bitswan/gitops:2024-11950964487-git-7e7eb51
  #   restart: always
  #   ports:
  #     - "8079:8079"
  #   volumes:
  #     - /path/to/repo:/repo # Change this to the path of your repository
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /etc/bitswan-secrets/:/etc/bitswan-secrets/
  #     - ${HOME}/.gitconfig:/root/.gitconfig
  #   environment:
  #     - BS_BITSWAN_DIR=/repo
  #     - BS_HOST_DIR=/path/to/repo # Change this to the path of your repository
  #     - MQTT_BROKER=emqx
  #     - MQTT_TOPIC=/c/local/running-pipelines/topology


networks:
  default:
    external: false
