#!/bin/bash
uv run python /app/manage.py collectstatic --noinput
uv run python /app/manage.py migrate

exec uv run gunicorn config.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker
