# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/compose/master/compose/config/compose_spec.json

volumes:
  aoc_local_bitswan_backend_postgres_data: {}
  aoc_local_bitswan_backend_postgres_data_backups: {}
  aoc_local_portainer_data:
  aoc_local_influx_data:
  aoc_local_influx_config:
  aoc_local_emqx_data:
  aoc_local_keycloak_postgres_data: {}
  aoc_local_keycloak_postgres_data_backups: {}

services:
  django:
    build:
      context: ../django
      dockerfile: ./compose/local/django/Dockerfile
    container_name: aoc-local-bitswan-backend
    restart: always
    depends_on:
      bitswan-backend-postgres:
        condition: service_started
      redis:
        condition: service_started
      keycloak-health:
        condition: service_completed_successfully
    volumes:
      - ../django:/app:z
      - ../django/compose/local/rathole/server.toml:/etc/rathole/rathole.toml:z
      - ../django/compose/local/traefik/config/routes.yml:/etc/traefik/routes.yaml:z
      - /var/run/docker.sock:/var/run/docker.sock:rw

    env_file:
      - envs/bitswan-backend.env
      - envs/bitswan-backend-postgres.env
    ports:
      - "8000:8000"
      - "5678:5678"
    command: /start

  bitswan-backend-postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: aoc-local-bitswan-backend-postgres
    restart: always
    volumes:
      - aoc_local_bitswan_backend_postgres_data:/var/lib/postgresql/data
      - aoc_local_bitswan_backend_postgres_data_backups:/backups
    env_file:
      - envs/bitswan-backend-postgres.env
    ports:
      - 5432:5432

  keycloak-postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    container_name: aoc-local-keycloak-postgres
    volumes:
      - aoc_local_keycloak_postgres_data:/var/lib/postgresql/data
      - aoc_local_keycloak_postgres_data_backups:/backups
    env_file: envs/keycloak-postgres.env
    ports:
      - 5434:5432

  redis:
    image: docker.io/redis:6
    container_name: aoc-local-redis
    ports:
      - 6379:6379

  influxdb:
    image: influxdb:2.0
    restart: always
    container_name: aoc-local-influxdb
    ports:
      - "8086:8086"
    volumes:
      - aoc_local_influx_data:/var/lib/influxdb2
      - aoc_local_influx_config:/etc/influxdb2
    env_file:
      - envs/influxdb.env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

  portainer:
    image: portainer/portainer-ce:latest
    container_name: aoc-local-portainer
    volumes:
      - aoc_local_portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always

  emqx:
    image: emqx:latest
    container_name: aoc-local-emqx
    restart: "no"
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    env_file:
      - envs/emqx.env
    volumes:
      - aoc_local_emqx_data:/opt/emqx/data
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    restart: always
    container_name: aoc-local-keycloak
    ports:
      - "9000:9000"
      - "8080:8080"
    env_file:
      - envs/keycloak.env
    command: start-dev

  keycloak-health:
    image: curlimages/curl:latest
    depends_on:
      - keycloak
    restart: "no"
    volumes:
      - ./scripts/keycloak-healthcheck.sh:/healthcheck.sh
    entrypoint: ["/healthcheck.sh"]
    network_mode: "host"

  profile-manager:
    restart: always
    build:
      context: ../profile-manager
      dockerfile: ./Dockerfile
    env_file:
      - ./envs/profile-manager.env

  aoc-nextjs:
    build:
      context: ../nextjs
      dockerfile: ./dev.dockerfile
    container_name: aoc-local-nextjs
    env_file:
      - ./envs/operations-centre.env
    ports:
      - "3000:3000"
    volumes:
      - ../nextjs:/app:z
      - /app/node_modules
