version: "3"

volumes:
  bitswan_backend_local_postgres_data: {}
  bitswan_backend_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ../django
      dockerfile: ./compose/local/django/Dockerfile
    image: bitswan_backend_local_django
    container_name: bitswan_backend_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
      - ./compose/local/rathole/server.toml:/etc/rathole/rathole.toml:z
      - ./compose/local/traefik/config/routes.yml:/etc/traefik/routes.yaml:z
      - /var/run/docker.sock:/var/run/docker.sock:rw

    env_file:
      - ./.envs/.local/.django.env
      - ./.envs/.local/.postgres.env
    ports:
      - "8000:8000"
      - "5678:5678"
    command: /start

  postgres:
    build:
      context: ../django
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bitswan_backend_production_postgres
    container_name: bitswan_backend_local_postgres
    volumes:
      - bitswan_backend_local_postgres_data:/var/lib/postgresql/data
      - bitswan_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres.env
    ports:
      - 5434:5432

  docs:
    image: bitswan_backend_local_docs
    container_name: bitswan_backend_local_docs
    build:
      context: ../django
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django.env
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bitswan_backend:/app/bitswan_backend:z
    ports:
      - "9060:9000"
    command: /start-docs

  redis:
    image: docker.io/redis:6
    container_name: bitswan_backend_local_redis
    ports:
      - 6379:6379
