# Generated by Django 4.2.10 on 2025-08-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitops', '0004_delete_brokers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gitops',
        ),
    ]
