[env]
_.python.venv = { path = "venv", create = true }

[tools]
python = '3.12.6'


[tasks.install]
description = "Installs django dependencies"
alias = "i"
run = "pip install -r ./requirements/local.txt"

[tasks.migrate]
description = "Runs django migrations"
run = "python manage.py migrate"

[tasks.runserver]
description = "Runs django server"
run = """
export $(grep -v '^#' .env | xargs)
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
python manage.py runserver
"""
