# Generated by Django 4.2.10 on 2025-08-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0011_groupnavigation_remove_usergroup_broker_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO core_groupnavigation (id, group_id, nav_items)
            SELECT id, group_id, nav_items FROM brokers_groupnavigation;
            """,
            reverse_sql="""
            INSERT INTO brokers_groupnavigation (id, group_id, nav_items)
            SELECT id, group_id, nav_items FROM core_groupnavigation;
            """,
        ),
    ]
