# Generated by Django 4.2.10 on 2025-08-11 12:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationServer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("automation_server_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("keycloak_org_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroupNavigation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.CharField(max_length=255, unique=True)),
                ("nav_items", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("keycloak_org_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("editor_url", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "automation_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="core.automationserver",
                        to_field="automation_server_id",
                    ),
                ),
            ],
        ),
    ]
