# Generated by Django 4.2.10 on 2025-08-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGroupMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keycloak_group_id', models.CharField(max_length=255, unique=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationServerGroupMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keycloak_group_id', models.CharField(max_length=255, unique=True)),
                ('automation_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.automationserver')),
            ],
        ),
    ]
