# Generated by Django 4.2.10 on 2025-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workspacegroupmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationservergroupmembership',
            name='keycloak_group_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workspacegroupmembership',
            name='keycloak_group_id',
            field=models.CharField(max_length=255),
        ),
    ]
