# Generated by Django 4.2.24 on 2025-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_automationservergroupmembership_keycloak_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationserver',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationserver',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='automationserver',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationserver',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
