# Generated by Django 4.2.24 on 2025-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_otp_token_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationserver',
            name='otp',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
