# Generated by Django 4.2.24 on 2025-10-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_increase_otp_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='keycloak_internal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
