name: BitSwan Backend Build and Push

on:
  push:
    branches: [main]
    tags: ["v*"]
    paths:
      - "django/**"
      - ".github/workflows/django.yml"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/new-cli') && github.event_name == 'push'
    services:
      docker:
        image: docker:20.10.7-dind
        options: --privileged
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push
        env:
          IMAGE_TAG: "bitswan/bitswan-backend"
          DOCKER_FILE: "./Dockerfile"
        run: |
          cd django
          bash ../build_and_push.sh
