name: CI Pipeline

on:
  push:
    paths:
      - "django/**"
      - ".github/workflows/django.yml"

jobs:
  lint:
    name: Precommit Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Pre-Commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run Pre-Commit
        env:
          PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    services:
      docker:
        image: docker:20.10.7-dind
        options: --privileged
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push
      env:
        IMAGE_TAG: "bitswan/bitswan-backend"
        DOCKER_FILE: "./compose/production/django/Dockerfile"
      run: |
        cd django
        bash ../build_and_push.sh
